#pragma once

#define SOUND_LOOPS_INDEFINITELY -1

enum SoundName {
    SOUND_UI_CLICK,
    SOUND_DEATH,
    SOUND_MUSKET,
    SOUND_GUN,
    SOUND_EXPLOSION,
    SOUND_PICKAXE,
    SOUND_HAMMER,
    SOUND_BUILDING_PLACE,
    SOUND_SWORD,
    SOUND_PUNCH,
    SOUND_DEATH_CHICKEN,
    SOUND_CANNON,
    SOUND_BUILDING_DESTROY,
    SOUND_BUNKER_DESTROY,
    SOUND_MINE_DESTROY,
    SOUND_MINE_INSERT,
    SOUND_MINE_ARM,
    SOUND_MINE_PRIME,
    SOUND_SMOKE,
    SOUND_THROW,
    SOUND_FLAG_THUMP,
    SOUND_GARRISON_IN,
    SOUND_GARRISON_OUT,
    SOUND_ALERT_BELL,
    SOUND_ALERT_BUILDING,
    SOUND_ALERT_RESEARCH,
    SOUND_ALERT_UNIT,
    SOUND_GOLD_MINE_COLLAPSE,
    SOUND_UNIT_HEY,
    SOUND_UNIT_OK,
    SOUND_UNIT_HAW,
    SOUND_MOLOTOV_IMPACT,
    SOUND_FIRE_BURN,
    SOUND_PISTOL_SILENCED,
    SOUND_COUNT
};

bool sound_init();
void sound_quit();
int sound_play(SoundName sound, int loops = 0);
bool sound_is_looping(SoundName sound);
void sound_begin_loop(SoundName sound);
void sound_end_loop(SoundName sound);