#pragma once

#include "defines.h"

enum AtlasName {
    ATLAS_UI,
    ATLAS_TILESET,
    ATLAS_MISC,
    ATLAS_UNIT_WAGON,
    ATLAS_FONT,
    ATLAS_COUNT
};

enum AtlasImportStrategy {
    ATLAS_IMPORT_DEFAULT,
    ATLAS_IMPORT_RECOLOR,
    ATLAS_IMPORT_RECOLOR_AND_LOW_ALPHA,
    ATLAS_IMPORT_TILESET,
    ATLAS_IMPORT_FONTS
};

struct AtlasParamsTileset {
    int begin;
    int end;
};

struct AtlasParams {
    const char* path;
    AtlasImportStrategy strategy;
    union {
        AtlasParamsTileset tileset;
    };
};

enum SpriteName {
    SPRITE_UI_MINIMAP,
    SPRITE_UI_BUTTON_PANEL,
    SPRITE_UI_BOTTOM_PANEL,
    SPRITE_UI_FRAME,
    SPRITE_UI_FRAME_SMALL,
    SPRITE_UI_BUTTON_REFRESH,
    SPRITE_UI_BUTTON_ARROW,
    SPRITE_UI_BUTTON_BURGER,
    SPRITE_UI_GOLD_ICON,
    SPRITE_UI_HOUSE_ICON,
    SPRITE_UI_MINER_ICON,
    SPRITE_UI_DROPDOWN,
    SPRITE_UI_DROPDOWN_MINI,
    SPRITE_UI_TEAM_PICKER,
    SPRITE_UI_PANEL_BUTTON,
    SPRITE_UI_MENU_BUTTON,
    SPRITE_UI_TEXT_FRAME,
    SPRITE_UI_CLOUDS,
    SPRITE_UI_SKY,
    SPRITE_GOLDMINE,
    SPRITE_UNIT_WAGON,
    SPRITE_TILE_NULL,
    SPRITE_TILE_SAND,
    SPRITE_TILE_SAND2,
    SPRITE_TILE_SAND3,
    SPRITE_TILE_WATER,
    SPRITE_TILE_WALL_NW_CORNER,
    SPRITE_TILE_WALL_NE_CORNER,
    SPRITE_TILE_WALL_SW_CORNER,
    SPRITE_TILE_WALL_SE_CORNER,
    SPRITE_TILE_WALL_NORTH_EDGE,
    SPRITE_TILE_WALL_WEST_EDGE,
    SPRITE_TILE_WALL_EAST_EDGE,
    SPRITE_TILE_WALL_SOUTH_EDGE,
    SPRITE_TILE_WALL_SE_FRONT,
    SPRITE_TILE_WALL_SOUTH_FRONT,
    SPRITE_TILE_WALL_SW_FRONT,
    SPRITE_TILE_WALL_NW_INNER_CORNER,
    SPRITE_TILE_WALL_NE_INNER_CORNER,
    SPRITE_TILE_WALL_SW_INNER_CORNER,
    SPRITE_TILE_WALL_SE_INNER_CORNER,
    SPRITE_TILE_WALL_SOUTH_STAIR_LEFT,
    SPRITE_TILE_WALL_SOUTH_STAIR_CENTER,
    SPRITE_TILE_WALL_SOUTH_STAIR_RIGHT,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_LEFT,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_CENTER,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_RIGHT,
    SPRITE_TILE_WALL_NORTH_STAIR_LEFT,
    SPRITE_TILE_WALL_NORTH_STAIR_CENTER,
    SPRITE_TILE_WALL_NORTH_STAIR_RIGHT,
    SPRITE_TILE_WALL_EAST_STAIR_TOP,
    SPRITE_TILE_WALL_EAST_STAIR_CENTER,
    SPRITE_TILE_WALL_EAST_STAIR_BOTTOM,
    SPRITE_TILE_WALL_WEST_STAIR_TOP,
    SPRITE_TILE_WALL_WEST_STAIR_CENTER,
    SPRITE_TILE_WALL_WEST_STAIR_BOTTOM,
    SPRITE_TILE_DECORATION0,
    SPRITE_TILE_DECORATION1,
    SPRITE_TILE_DECORATION2,
    SPRITE_TILE_DECORATION3,
    SPRITE_TILE_DECORATION4,
    SPRITE_COUNT
};

struct SpriteInfo {
    AtlasName atlas;
    int atlas_x;
    int atlas_y;
    int frame_width;
    int frame_height;
};

enum TileType {
    TILE_TYPE_SINGLE,
    TILE_TYPE_AUTO
};

struct TileData {
    TileType type;
    int source_x;
    int source_y;
};

const AtlasParams& resource_get_atlas_params(AtlasName atlas);
const SpriteInfo& resource_get_sprite_info(SpriteName name);
void resource_set_sprite_info(SpriteName name, SpriteInfo sprite_info);
const TileData& resource_get_tile_data(SpriteName tile);