#pragma once

#include "defines.h"

enum Tileset {
    TILESET_ARIZONA,
    TILESET_FOG,
    TILESET_COUNT
};

enum SpriteName {
    SPRITE_TILE_NULL,
    SPRITE_TILE_SAND1,
    SPRITE_TILE_SAND2,
    SPRITE_TILE_SAND3,
    SPRITE_TILE_WATER,
    SPRITE_TILE_WALL_NW_CORNER,
    SPRITE_TILE_WALL_NE_CORNER,
    SPRITE_TILE_WALL_SW_CORNER,
    SPRITE_TILE_WALL_SE_CORNER,
    SPRITE_TILE_WALL_NORTH_EDGE,
    SPRITE_TILE_WALL_WEST_EDGE,
    SPRITE_TILE_WALL_EAST_EDGE,
    SPRITE_TILE_WALL_SOUTH_EDGE,
    SPRITE_TILE_WALL_SE_FRONT,
    SPRITE_TILE_WALL_SOUTH_FRONT,
    SPRITE_TILE_WALL_SW_FRONT,
    SPRITE_TILE_WALL_NW_INNER_CORNER,
    SPRITE_TILE_WALL_NE_INNER_CORNER,
    SPRITE_TILE_WALL_SW_INNER_CORNER,
    SPRITE_TILE_WALL_SE_INNER_CORNER,
    SPRITE_TILE_WALL_SOUTH_STAIR_LEFT,
    SPRITE_TILE_WALL_SOUTH_STAIR_CENTER,
    SPRITE_TILE_WALL_SOUTH_STAIR_RIGHT,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_LEFT,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_CENTER,
    SPRITE_TILE_WALL_SOUTH_STAIR_FRONT_RIGHT,
    SPRITE_TILE_WALL_NORTH_STAIR_LEFT,
    SPRITE_TILE_WALL_NORTH_STAIR_CENTER,
    SPRITE_TILE_WALL_NORTH_STAIR_RIGHT,
    SPRITE_TILE_WALL_EAST_STAIR_TOP,
    SPRITE_TILE_WALL_EAST_STAIR_CENTER,
    SPRITE_TILE_WALL_EAST_STAIR_BOTTOM,
    SPRITE_TILE_WALL_WEST_STAIR_TOP,
    SPRITE_TILE_WALL_WEST_STAIR_CENTER,
    SPRITE_TILE_WALL_WEST_STAIR_BOTTOM,
    SPRITE_DECORATION,
    SPRITE_FOG_HIDDEN,
    SPRITE_FOG_EXPLORED,
    SPRITE_UI_MINIMAP,
    SPRITE_UI_BUTTON_PANEL,
    SPRITE_UI_BOTTOM_PANEL,
    SPRITE_UI_FRAME,
    SPRITE_UI_FRAME_SMALL,
    SPRITE_UI_BUTTON_REFRESH,
    SPRITE_UI_BUTTON_ARROW,
    SPRITE_UI_BUTTON_BURGER,
    SPRITE_UI_GOLD_ICON,
    SPRITE_UI_HOUSE_ICON,
    SPRITE_UI_MINER_ICON,
    SPRITE_UI_DROPDOWN,
    SPRITE_UI_DROPDOWN_MINI,
    SPRITE_UI_TEAM_PICKER,
    SPRITE_UI_MENU_BUTTON,
    SPRITE_UI_TEXT_FRAME,
    SPRITE_UI_CLOUDS,
    SPRITE_UI_SWATCH,
    SPRITE_UI_TITLE,
    SPRITE_SELECT_RING_LANDMINE,
    SPRITE_SELECT_RING_LANDMINE_ATTACK,
    SPRITE_SELECT_RING_UNIT,
    SPRITE_SELECT_RING_UNIT_ATTACK,
    SPRITE_SELECT_RING_WAGON,
    SPRITE_SELECT_RING_WAGON_ATTACK,
    SPRITE_SELECT_RING_BUILDING_SIZE2,
    SPRITE_SELECT_RING_BUILDING_SIZE2_ATTACK,
    SPRITE_SELECT_RING_BUILDING_SIZE3,
    SPRITE_SELECT_RING_BUILDING_SIZE3_ATTACK,
    SPRITE_SELECT_RING_BUILDING_SIZE4,
    SPRITE_SELECT_RING_BUILDING_SIZE4_ATTACK,
    SPRITE_SELECT_RING_GOLDMINE,
    SPRITE_GOLDMINE,
    SPRITE_UNIT_WAGON,
    SPRITE_UNIT_MINER,
    SPRITE_COUNT
};

enum SpriteImportStrategy {
    SPRITE_IMPORT_DEFAULT,
    SPRITE_IMPORT_RECOLOR,
    SPRITE_IMPORT_RECOLOR_AND_LOW_ALPHA,
    SPRITE_IMPORT_TILE
};

struct SpriteParamsSheet {
    const char* path;
    int hframes;
    int vframes;
};

enum TileType {
    TILE_TYPE_SINGLE,
    TILE_TYPE_AUTO
};

struct SpriteParamsTile {
    Tileset tileset;
    TileType type;
    int source_x;
    int source_y;
};

struct SpriteParams {
    SpriteImportStrategy strategy;
    union {
        SpriteParamsSheet sheet;
        SpriteParamsTile tile;
    };
};

struct TilesetParams {
    const char* path;
};

const SpriteParams& render_get_sprite_params(SpriteName sprite);
const TilesetParams& render_get_tileset_params(Tileset tileset);