name: Build MacOS

on: 
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install sdl3 sdl3_image sdl3_ttf enet

      - name: Scaffold
        run: |
          make scaffold

      - name: Prep
        run: |
          make prep

      - name: Build
        run: |
          clang++ -v
          make RELEASE=true

      - name: Bundle
        run: |
          make macos-bundle
          echo "running ls"
          ls
          echo "running ls bin"
          ls ./bin
          zip -vr ./bin/goldrush_macos.zip ./bin/Gold\ Rush.app/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: goldrush_macos
          path: bin/goldrush_macos.zip

  deploy:
    needs: [build_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5

      - name: Unzip Artifacts
        run: |
          mkdir bin
          mkdir ./bin/goldrush_macos
          unzip ./goldrush_macos/goldrush_macos.zip -d ./bin/goldrush_macos
          echo "running ls ."
          ls
          echo "running ls ./bin"
          ls ./bin
          echo "running ls ./bin/goldrush_macos"
          ls ./bin/goldrush_macos